import Header from "@/components/common/Header";
import "./globals.css";
import SmoothScroll from "@/components/ui/SmoothScroll";

export const metadata = {
  title: "Falcon Calibration",
  description: "Generated by Falcon Calibration",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true}>
        <SmoothScroll>
          <Header />
          {children}
        </SmoothScroll>
      </body>
    </html>
  );
}
